language: python
python:
  - "3.3"
# command to install dependencies
install: "pip install -r requirements.txt"
before_script: 
  - "flake8 --max-complexity=5 manage.py sched/"
# command to run tests
script: 
  - coverage run --omit="/Library*" unit_test.py
  - nosetests --cover-package=manage,sched --with-doctest --with-coverage --cover-min-percentage=95
