language: python
python:
  - "2.7"
# command to install dependencies
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
install: "pip install -r requirements.txt"
before_script: 
  - "flake8 manage.py sched/"
# command to run tests
script: 
  - python manage.py runserver & lettuce tests
