language: python
python:
  - "2.7"
# command to install dependencies
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
install: "pip install -r requirements.txt"
before_script: 
  - "flake8 --max-complexity=4 manage.py sched/"
# command to run tests
script: 
  - lettuce tests
  - coverage run --omit="/Library*" unit_test.py
  - nosetests --cover-package=manage,sched --with-doctest --with-coverage --cover-min-percentage=95
after_success:
  - python manage.py runserver